### ISSUE TITLE
请问在《理解prototype和__proto__》中用的是什么画图工具啊

### ISSUE THREAD

**Issue by JerryC8080** [dreamapplehappy/hacking-with-javascript#1]

**Comment by dreamapplehappy** [comment]
@JerryC8080 使用的是这个[http://pythontutor.com/visualize.html#mode=edit](http://pythontutor.com/visualize.html#mode=edit)，很不错的一个在线编辑器，重要的是可以看清你的代码在电脑内存中是如何运行的:grinning:。

**Comment by JerryC8080** [comment]
@dreamapplehappy  很赞的工具啊，我一直在寻找像这样的工具。🙏🏽谢啦！
