### ISSUE TITLE
掌握JavaScript函数的柯里化

### ISSUE THREAD

**Issue by dreamapplehappy** [dreamapplehappy/hacking-with-javascript#2]
大家有什么疑问，建议或者批评指正，都可以在下面提出来:grin:

**Comment by forclan** [comment]
🍊柯里化的一些应用场景  这节中，往下第四行“一般情况下,我们如果想给一个setTimeout传递进来的函数添加参数的话,一般会使用_**之**_种方法:应该为“这种”

**Comment by dreamapplehappy** [comment]
@forclan 谢谢纠错，我修改一下。
