### ISSUE TITLE
item 13: 使用立即调用的函数表达式创建新的作用域 (Use Immediately Invoked Function Expressions to Create Local Scopes)

### ISSUE THREAD

**Issue by mengyou658** [dreamapplehappy/hacking-with-javascript#6]
// 测试使用的数组
var testArr = [1, 2, 3];

// @3 使用闭包方式二
function generateFunc2(arr) {
var result = [];
var n = arr.length;
for(var i = 0; i < n; i++) {
(function() {
result[i] = function() {
return arr[i];
}
})()
}
return result;
}
// @3 产生新的函数
var g3 = generateFunc2(testArr);
console.log(g30); // 1
console.log(g31); // 2
console.log(g32); // 3
VM14910:19 undefined
VM14910:20 undefined
VM14910:21 undefined
undefined

chrome版本 54.0.2840.87 m (64-bit)

这里执行的结果还是undefined

**Comment by dreamapplehappy** [comment]
@mengyou658 [我的一个错误](https://github.com/dreamapplehappy/effective-javascript/issues/2) 已经解决了。
